# Build the flask backend container
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY api/. ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production
ENV FLASK_APP=main.py

EXPOSE 8080

# Start the application
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--timeout", "360", "main:app"]